version: '3'
services:
  postgres-db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    container_name: bms_postgress_v2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=evsbvFm3QR

volumes:
  pgdata: